services:
  - type: web
    name: talabat-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://talabat-server.onrender.com/api
      - key: NODE_ENV
        value: production
